services:
  db:
    image: postgres:18
    container_name: lab01_postgres_practice
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "sakila"
    ports:
    - "5432:5432"
    volumes:
      # Nombre del volume para persistencia
      - pg_data:/var/lib/postgresql
      # scripts iniciales
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sakila"]
      interval: 5s
      timeout: 3s
      retries: 20
  web:
    build: ./web
    container_name: lab01_web_practice
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
    pg_data: